import { Button, HorizontalBox, TextEdit, ComboBox } from "std-widgets.slint";

export component MainWindow inherits Window {
    in property <string> log;  // 游戏输出日志
    in-out property <string> game_mode: "经不了一典64方块";  // 游戏启动类型
    in-out property <string> ua: "...";  // 游戏运行客户端类型
    callback new-game;  // 新建游戏
    width: 800px;
    height: 600px;
    title: "rust craft 2d 游戏启动器";
    // icon: @image-url("icon.png");
    VerticalLayout {
        // alignment: center;
        // 标题
        Text {
            vertical-alignment: center;
            horizontal-alignment: center;
            font-size: 30px;
            text: "rust craft 2d 游戏启动器";
            // color: green;
        }
        // 模式选择
        HorizontalBox {
            alignment: center;
            Text {
                vertical-alignment: center;
                horizontal-alignment: center;
                text: "游戏模式：";
                color: black;
            }
            ComboBox {
                width: 150.0px;
                height: 25.0px;
                model: ["经不了一典64方块", "无尽方块"];
                current-value: "经不了一典64方块";
                selected(current-value)=>{game_mode = current_value}
            }
        }
        
        // 启动按钮集
        HorizontalBox {
            alignment: center;
            Button {
                text:"新建游戏";
                height: 50px;
                width: 150px;
                clicked=>{root.new-game();}
            }
        }
        // 游戏日志显示
        Text {
            vertical-alignment: center;
            horizontal-alignment: center;
            text: "游戏日志";
            color: orange;
        }
        HorizontalLayout {
            alignment: center;
            width: parent.width;
            height: parent.height * 0.5;
            TextEdit {
                text: root.log;
                width: parent.width * 0.6;
                height: parent.height;
                read-only: false;
            }
        }
        // 底部信息显示
        HorizontalLayout {
            Text {
                vertical-alignment: center;
                horizontal-alignment: center;
                text: "当前启动器适配游戏版本: v0.3.1(demo)";
                color: green;
            }
            Text {
                vertical-alignment: center;
                horizontal-alignment: center;
                text: "客户端: " + ua;
                color: green;
            }
        }
    }
}
